version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./confs/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - demo-service
    links:
      - demo-service
    ports:
      - 80:80
    networks:
      - spring-cloud-network

  demo-service:
    networks:
      - spring-cloud-network
    build:
      context: .
      dockerfile: confs/Dockerfile


networks:
  spring-cloud-network:
    driver: bridge